# Generated by Django 3.1.7 on 2021-04-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intranetIP', models.GenericIPAddressField(protocol='ipv4')),
                ('extrantIP', models.GenericIPAddressField(null=True, protocol='ipv4')),
                ('serverType', models.CharField(max_length=10)),
                ('serverPurpose', models.CharField(max_length=32)),
                ('serverAccount', models.CharField(max_length=32)),
                ('serverPassword', models.CharField(max_length=32)),
                ('serverOs', models.CharField(max_length=32)),
                ('originServer', models.CharField(max_length=32, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
