# Generated by Django 3.1.7 on 2021-04-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('auth_id', models.AutoField(default=10000, primary_key=True, serialize=False)),
                ('authname', models.CharField(max_length=32)),
                ('authcode', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('telephoneNum', models.IntegerField(null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('auth_rel', models.ManyToManyField(to='commonManage.Auth')),
            ],
        ),
    ]
