# Generated by Django 3.1.7 on 2021-03-29 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvInfo',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('env_name', models.CharField(db_index=True, max_length=32)),
                ('frontIP', models.GenericIPAddressField(protocol='ipv4')),
                ('backIP', models.GenericIPAddressField(protocol='ipv4')),
                ('dbIP', models.GenericIPAddressField(protocol='ipv4')),
                ('status', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intranetIP', models.GenericIPAddressField(protocol='ipv4')),
                ('extrantIP', models.GenericIPAddressField(null=True, protocol='ipv4')),
                ('serverType', models.CharField(max_length=10)),
                ('serverPurpose', models.CharField(max_length=32)),
                ('serverAccount', models.CharField(max_length=32)),
                ('serverPassword', models.CharField(max_length=32)),
                ('serverOs', models.CharField(max_length=32)),
                ('originServer', models.CharField(max_length=32, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('telephoneNum', models.IntegerField(null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvDetailInfo',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_chinese_name', models.CharField(db_index=True, max_length=32)),
                ('service_name', models.CharField(db_index=True, max_length=32)),
                ('service_host', models.GenericIPAddressField(protocol='ipv4')),
                ('service_port', models.IntegerField()),
                ('service_deploy_path', models.CharField(max_length=200)),
                ('service_url', models.CharField(max_length=50)),
                ('service_model', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('env_sub_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.envinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DbInfo',
            fields=[
                ('db_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(db_index=True, protocol='ipv4')),
                ('port', models.IntegerField()),
                ('sid', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('db_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.envinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('auth_id', models.AutoField(default=10000, primary_key=True, serialize=False)),
                ('authname', models.CharField(max_length=32)),
                ('authcode', models.CharField(max_length=32)),
                ('r', models.ManyToManyField(to='machine.UserInfo')),
            ],
        ),
    ]
