# Generated by Django 3.0.6 on 2020-08-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='telephoneNum',
            field=models.IntegerField(null=True),
        ),
    ]
