# Generated by Django 3.1 on 2020-08-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbinfo',
            name='db_name',
        ),
    ]
