# Generated by Django 3.1.7 on 2021-03-30 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20210330_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_auth_rel',
            new_name='auth_rel',
        ),
    ]
