# Generated by Django 3.1.7 on 2021-04-01 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvInfo',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('env_name', models.CharField(db_index=True, max_length=32)),
                ('frontIP', models.GenericIPAddressField(protocol='ipv4')),
                ('backIP', models.GenericIPAddressField(protocol='ipv4')),
                ('dbIP', models.GenericIPAddressField(protocol='ipv4')),
                ('status', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='EnvDetailInfo',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_chinese_name', models.CharField(db_index=True, max_length=32)),
                ('service_name', models.CharField(db_index=True, max_length=32)),
                ('service_host', models.GenericIPAddressField(protocol='ipv4')),
                ('service_port', models.IntegerField()),
                ('service_deploy_path', models.CharField(max_length=200)),
                ('service_url', models.CharField(max_length=50)),
                ('service_model', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('env_sub_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envManage.envinfo')),
            ],
        ),
        migrations.CreateModel(
            name='DbInfo',
            fields=[
                ('db_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(db_index=True, protocol='ipv4')),
                ('port', models.IntegerField()),
                ('sid', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('db_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envManage.envinfo')),
            ],
        ),
    ]
